# Generated by Django 2.0 on 2019-01-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0002_auto_20190101_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watsons.Customer')),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='check_date',
            new_name='time',
        ),
    ]
