# Generated by Django 2.0 on 2019-01-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0005_auto_20190103_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(default='n', max_length=10),
            preserve_default=False,
        ),
    ]
