# Generated by Django 2.0 on 2019-01-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0006_location_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='marketing_spending',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
