# Generated by Django 2.0 on 2019-01-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0007_customer_marketing_spending'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
