# Generated by Django 2.0 on 2019-01-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0013_pocket_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='frequency_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='recent_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
