# Generated by Django 2.0 on 2019-01-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0014_auto_20190107_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='amount_num',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='frequency_num',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='recent_num',
        ),
    ]
