# Generated by Django 2.0 on 2019-01-08 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0015_auto_20190107_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='last_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.TextField(default='100000000'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_safe',
            field=models.IntegerField(default=1),
        ),
    ]
