# Generated by Django 2.0 on 2019-01-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0017_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num', models.IntegerField(default=0)),
                ('Date', models.IntegerField(default=0)),
            ],
        ),
    ]
