# Generated by Django 2.0 on 2019-01-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0018_servive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='marketing_spending',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
