# Generated by Django 2.0 on 2019-01-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0020_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pocket_other',
            old_name='total_other',
            new_name='total_Care',
        ),
        migrations.RemoveField(
            model_name='pocket_other',
            name='product',
        ),
        migrations.AddField(
            model_name='pocket_other',
            name='total_Cosmetic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pocket_other',
            name='total_Snacks',
            field=models.IntegerField(default=0),
        ),
    ]
